[package]
name = "testyo"
version = "0.1.0"
edition = "2024"

[dependencies]
glfw = "0.61.0"
wgpu = "28.0.0"
glam = "0.31.0"
tokio = { version = "1.49.0", features = ["rt", "rt-multi-thread", "macros"] }
